export const moviesData = [
  {
    id: 1,
    title: 'Inception',
    genre: 'Sci-Fi, Action',
    length: '2h 28min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/inception.jpg',
    ticketPrice: '$14.99',
    rating: 4.5,
    likesPercentage: 90,
  },
  {
    id: 2,
    title: 'The Shawshank Redemption',
    genre: 'Drama',
    length: '2h 22min',
    posterUrl: 'https://m.media-amazon.com/images/I/61e2VQ34dML._AC_UF1000,1000_QL80_.jpg',
    ticketPrice: '$12.99',
    rating: 4.8,
    likesPercentage: 95,
  },
  {
    id: 3,
    title: 'The Dark Knight',
    genre: 'Action, Crime',
    length: '2h 32min',
    posterUrl: 'https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/S/pv-target-images/57618417a0ddf3b7aa29db658bef2fc3b9608bb11a021631d3b6408441c1e0f7.jpg',
    ticketPrice: '$16.99',
    rating: 4.7,
    likesPercentage: 88,
  },
  {
    id: 4,
    title: 'Interstellar',
    genre: 'Sci-Fi, Drama',
    length: '2h 49min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/interstellar.jpg',
    ticketPrice: '$15.99',
    rating: 4.6,
    likesPercentage: 92,
  },
  {
    id: 5,
    title: 'Pulp Fiction',
    genre: 'Crime, Drama',
    length: '2h 34min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/pulp_fiction.jpg',
    ticketPrice: '$13.99',
    rating: 4.9,
    likesPercentage: 97,
  },
  {
    id: 6,
    title: 'Forrest Gump',
    genre: 'Drama, Romance',
    length: '2h 22min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/forrest_gump.jpg',
    ticketPrice: '$11.99',
    rating: 4.5,
    likesPercentage: 88,
  },
  {
    id: 7,
    title: 'The Matrix',
    genre: 'Action, Sci-Fi',
    length: '2h 16min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/matrix.jpg',
    ticketPrice: '$14.99',
    rating: 4.7,
    likesPercentage: 91,
  },
  {
    id: 8,
    title: 'The Godfather',
    genre: 'Crime, Drama',
    length: '2h 55min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/godfather.jpg',
    ticketPrice: '$17.99',
    rating: 4.9,
    likesPercentage: 98,
  },
  {
    id: 9,
    title: 'Fight Club',
    genre: 'Drama',
    length: '2h 19min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/fight_club.jpg',
    ticketPrice: '$12.99',
    rating: 4.8,
    likesPercentage: 94,
  },
  {
    id: 10,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    genre: 'Action, Adventure, Drama',
    length: '2h 58min',
    posterUrl: 'https://www.movieposters.com/cdn/shop/files/lotr_fellowship.jpg',
    ticketPrice: '$18.99',
    rating: 4.9,
    likesPercentage: 96,
  },
];
